8 exclusao de escola
fga-eps-mds/2023.1-Dnit-EscolaService pull request #10
Opened 2023-06-12 02:53 UTC by lhuck4z

## Issue :_8

Resolves fga-eps-mds/2023.1-DNIT-EscolaService#8

 

## Descrição
Implementação da função de excluir uma escola cadastrada
## Imagens:
### Escola cadastrada:
![escolacastrada](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/b714918b-9a1f-4de5-a76e-3e3e3846447d)
### Endpoint para excluir escola cadastrada:
![Captura de tela 2023-06-10 151823](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/6913a759-d332-4315-be62-a75fe9175a1c)
![swagger](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/525fe555-b1f8-4eed-a77e-03a25d498ffb)
### Escola excluída:
![escolaexcluida](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/00dee95e-3b13-4b89-af29-e4cfe0bf4210)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [x] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-14 03:46 UTC, DenysRogeres requested changes
Mandaram beeem! Mas há alguns itens que voces devem resolver.

2023-06-14 03:46 UTC, DenysRogeres commented on app/Controllers/EscolaController.cs
> +        public IEnumerable<EscolaCadastrada> Ler()
Qual o sentido do nome desse método? Acredito que "Ler" fica muio humanizado, pelo que entendi esse método retornar as escolas, não ficaria melhor simplesmente "listar"? Além disso, por qual motivo não tem um try catch nesse método?

2023-06-14 03:46 UTC, DenysRogeres commented on app/Controllers/EscolaController.cs
> +        public IActionResult Excluir(ExclusaoEscola exclusaoEscola)
Aqui o nome tá bom, no entanto, faltou o try catch dentro do método para tratar a exceção. Outra coisa, vocês criaram a classe ExclusaoEscola mas ela só tem uma propriedade que é um inteiro, pq não deixa simplesmente o inteiro aqui então?

2023-06-14 03:46 UTC, DenysRogeres commented on app/DI/RepositoriosConfig.cs
> +            services.AddScoped<IEscolaRepositorio, EscolaRepositorio>();
Já estão fazendo fazer injeção de dependências. Braboooos!

2023-06-14 03:46 UTC, DenysRogeres commented on app/DI/ServicesConfig.cs
> +            services.AddScoped<IEscolaService, EscolaService>();
Dominaram a injeção de depedências

2023-06-14 03:46 UTC, DenysRogeres commented on dominio/EscolaCadastrada.cs
> +        public string Endereco { get; set; }
Endereco ficou simplesmente como uma string mesmo?

2023-06-14 03:46 UTC, DenysRogeres commented on dominio/EscolaCadastrada.cs
> +        public int Codigo { get; set; }
Acredito que dependendo da implementação que vocês façam no front, essa classe vai ter que ser alterada, aqui eu não consigo enchegar como vamos tratar os campos de domínio. Precisamos fazer um double check com a equipe que tá fazendo a listagem lá no front

2023-06-14 03:46 UTC, DenysRogeres commented on dominio/ExclusaoEscola.cs
> +namespace dominio
Essa classe aqui fica sem sentido pq só tem uma propriedade, então podemos usar só int mesmo

2023-06-14 03:46 UTC, DenysRogeres commented on repositorio/EscolaRepositorio.cs
> +        {
Por qual motivo você precisa retornar o id da escola? O método ele somente excluí, então não precisa retornar nada, apenas retornar se foi com sucesso ou não. Caso dê algum erro, deve lançar um throw excetion pra cima que será tratada lá na controller

2023-06-14 03:46 UTC, DenysRogeres commented on repositorio/Interfaces/IEscolaRepositorio.cs
> +{
Aqui tá ok. Fica aqui uma observação de clean code. Quando eu leio "public IEnumerable<EscolaCadastrada> ObterEscolas();" eu sei que o retorno é uma lista enumerada de escolas cadastradas, neste caso, poderiamos deixar o método apenas como "Obter" mesmo. "ObterEscolas" ficaria redundante, mas isso não é algo errado não, só um ponto de clean code para vocês prestarem atenção. Além disso, por qual motivo o método excluir deveria retornar um inteiro? Neste caso, o nome do método poderia ser "ExcluirEscola" já que o parametro é simplesmente um inteiro. Ou então, caso fosse passada toda a "EscolaCadastrada" como parâmetro, poderiamos deixar o nome do método como " public void Excluir(EscolaCadastrada escola)", pq aí a escola tá sendo passada como parametro, então o que você vai excluir? >>>>Escola<<<<< (que esta no parametro)

2023-06-14 03:46 UTC, DenysRogeres commented on service/Interfaces/IEscolaService.cs
> +        public void Excluir(ExclusaoEscola exclusaoEscola);
Aqui o retorno tá como void, tá certo, só faltou corrigir no repositório.

2023-06-14 03:46 UTC, DenysRogeres commented on service/EscolaService.cs
> +            escolaRepositorio.Excluir(exclusaoEscola.Id);
Aqui você poderia passar toda a exclusãoEscola como parametro e lá no repositório usar só o ID. Mas essa classe vai morrer

2023-06-17 01:49 UTC, LeticiaResende23 commented on dominio/EscolaCadastrada.cs
> +        public string Endereco { get; set; }
Sim, no banco ainda está como uma string

2023-06-17 02:04 UTC, LeticiaResende23 commented
As correções foram feitas

2023-06-17 02:05 UTC, LeticiaResende23 commented
As correções foram feitas

2023-06-18 23:02 UTC, DenysRogeres approved these changes
Aprovado! Acabou faltando o tratamento de exceção na controller mas a gente faz isso quando for fazer os testes

2023-06-18 23:20 UTC, merged