5 implementação visualização escolas
fga-eps-mds/2023.1-Dnit-EscolaService pull request #11
Opened 2023-06-14 00:11 UTC by JuliaSSouza

## Issue :_5

Resolves fga-eps-mds/2023.1-DNIT-EscolaService#5

 

## Descrição
Implementação da função de exibir as escolas cadastradas
## Imagens:
### Escola cadastrada:
![TabelaEscolas](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88839152/188b7936-ed08-4f10-a21c-3993c44ddabb)
### Endpoint para exibir escola cadastrada:
![Endpoint](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88839152/7b9c5cc6-a3e6-4e30-ae4c-7a632ed547b4)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [x] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-14 13:42 UTC, lucas229 requested changes
Parabéns pelo trabalho! Tentem ajustar de acordo com essas sugestões que fiz.

2023-06-14 13:42 UTC, lucas229 commented on app/Controllers/EscolaController.cs
> +        public IEnumerable<EscolaCadastrada> Ler()
Aqui poderiam usar o mesmo nome que usaram no EscolaService. Pra manter a padronização, sugiro mudar o nome desse método pra Listar.

2023-06-14 13:42 UTC, lucas229 commented on dominio/EscolaCadastrada.cs
> +}
O nome EscolaCadastrada pode passar a impressão que o domínio tem alguma relação com o evento de cadastro de uma escola. Como o objetivo desse domínio é representar uma escola, sugiro renomear somente para Escola, pois indica de forma mais clara a finalidade dele.

Com relação ao nome dos atributos, há uma forma de mapear direto no comando SELECT que está no repositório. Nesse caso, não será mais necessário que os atributos da classe de domínio tenham o mesmo nome que as colunas da tabela no banco de dados.
```suggestion
namespace dominio
{
    public class Escola
    {
        public int IdEscola { get; set; }
        public int CodigoEscola { get; set; }
        public string NomeEscola { get; set; }
        public int IdRede { get; set; }
        public string Cep { get; set; }
        public int IdUf { get; set; }
        public string Endereco { get; set; }
        public int IdMunicipio { get; set; }
        public int IdLocalizacao { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int IdEtapasDeEnsino { get; set;} 
        public int NumeroTotalDeAlunos { get; set; }
        public int IdSituacao { get; set; }
        public int IdPorte { get; set; }
        public string Telefone { get; set; }
        public int NumeroTotalDeDocentes{ get; set; }
    }
}
```

2023-06-14 13:42 UTC, lucas229 commented on repositorio/EscolaRepositorio.cs
> +            var sql = @"SELECT * FROM public.escola";
Pra mapear as colunas da tabela da maneira que sugeri no domínio, na consulta SELECT podemos especificar o nome de cada dado que será recuperado do banco de dados:
```suggestion
            var sql = @"
                SELECT
                    nome_escola nomeEscola,
                    codigo_escola codigoEscola,
                    cep,
                    endereco,
                    latitude,
                    longitude,
                    numero_total_de_alunos numeroTotalDeAlunos,
                    telefone,
                    numero_total_de_docentes numeroTotalDeDocentes,
                    id_escola idEscola,
                    id_rede idRede,
                    id_uf idUf,
                    id_localizacao idLocalizacao,
                    id_municipio idMunicipio,
                    id_etapas_de_ensino idEtapasDeEnsino,
                    id_porte idPorte,
                    id_situacao idSituacao
                FROM
                    public.escola";
```

2023-06-14 13:42 UTC, lucas229 commented on repositorio/EscolaRepositorio.cs
> +        */
Foi uma boa percepção, porém o filtro será implementado de uma forma um pouco diferente. Da forma que está, apesar de funcionar, teríamos que fazer um método desse pra cada combinação de filtro.
Já que posteriormente os filtros vão ser feitos de uma maneira dinâmica pra evitar duplicação, sugiro remover o código comentado.

2023-06-14 13:42 UTC, lucas229 commented on repositorio/Interfaces/IEscolaRepositorio.cs
> +        */
Sugiro remover os métodos comentados da interface pelo mesmo motivo.

2023-06-14 17:51 UTC, Stain19 commented
As modificações sugeridas na revisão do código foram aplicadas @lucas229

2023-06-15 00:07 UTC, lucas229 approved these changes
Aprovado!

2023-06-15 01:56 UTC, merged